# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

"""These are the python bindings to the octra library"""

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _octra
else:
    import _octra

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


SHARED_PTR_DISOWN = _octra.SHARED_PTR_DISOWN
class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _octra.delete_SwigPyIterator

    def value(self):
        return _octra.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _octra.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _octra.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _octra.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _octra.SwigPyIterator_equal(self, x)

    def copy(self):
        return _octra.SwigPyIterator_copy(self)

    def next(self):
        return _octra.SwigPyIterator_next(self)

    def __next__(self):
        return _octra.SwigPyIterator___next__(self)

    def previous(self):
        return _octra.SwigPyIterator_previous(self)

    def advance(self, n):
        return _octra.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _octra.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _octra.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _octra.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _octra.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _octra.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _octra.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _octra:
_octra.SwigPyIterator_swigregister(SwigPyIterator)
class IPair(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _octra.IPair_swiginit(self, _octra.new_IPair(*args))
    first = property(_octra.IPair_first_get, _octra.IPair_first_set)
    second = property(_octra.IPair_second_get, _octra.IPair_second_set)
    def __len__(self):
        return 2
    def __repr__(self):
        return str((self.first, self.second))
    def __getitem__(self, index): 
        if not (index % 2):
            return self.first
        else:
            return self.second
    def __setitem__(self, index, val):
        if not (index % 2):
            self.first = val
        else:
            self.second = val
    __swig_destroy__ = _octra.delete_IPair

# Register IPair in _octra:
_octra.IPair_swigregister(IPair)
class IVec(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _octra.IVec_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _octra.IVec___nonzero__(self)

    def __bool__(self):
        return _octra.IVec___bool__(self)

    def __len__(self):
        return _octra.IVec___len__(self)

    def __getslice__(self, i, j):
        return _octra.IVec___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _octra.IVec___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _octra.IVec___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _octra.IVec___delitem__(self, *args)

    def __getitem__(self, *args):
        return _octra.IVec___getitem__(self, *args)

    def __setitem__(self, *args):
        return _octra.IVec___setitem__(self, *args)

    def pop(self):
        return _octra.IVec_pop(self)

    def append(self, x):
        return _octra.IVec_append(self, x)

    def empty(self):
        return _octra.IVec_empty(self)

    def size(self):
        return _octra.IVec_size(self)

    def swap(self, v):
        return _octra.IVec_swap(self, v)

    def begin(self):
        return _octra.IVec_begin(self)

    def end(self):
        return _octra.IVec_end(self)

    def rbegin(self):
        return _octra.IVec_rbegin(self)

    def rend(self):
        return _octra.IVec_rend(self)

    def clear(self):
        return _octra.IVec_clear(self)

    def get_allocator(self):
        return _octra.IVec_get_allocator(self)

    def pop_back(self):
        return _octra.IVec_pop_back(self)

    def erase(self, *args):
        return _octra.IVec_erase(self, *args)

    def __init__(self, *args):
        _octra.IVec_swiginit(self, _octra.new_IVec(*args))

    def push_back(self, x):
        return _octra.IVec_push_back(self, x)

    def front(self):
        return _octra.IVec_front(self)

    def back(self):
        return _octra.IVec_back(self)

    def assign(self, n, x):
        return _octra.IVec_assign(self, n, x)

    def resize(self, *args):
        return _octra.IVec_resize(self, *args)

    def insert(self, *args):
        return _octra.IVec_insert(self, *args)

    def reserve(self, n):
        return _octra.IVec_reserve(self, n)

    def capacity(self):
        return _octra.IVec_capacity(self)
    __swig_destroy__ = _octra.delete_IVec

# Register IVec in _octra:
_octra.IVec_swigregister(IVec)
class IIVec(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _octra.IIVec_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _octra.IIVec___nonzero__(self)

    def __bool__(self):
        return _octra.IIVec___bool__(self)

    def __len__(self):
        return _octra.IIVec___len__(self)

    def __getslice__(self, i, j):
        return _octra.IIVec___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _octra.IIVec___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _octra.IIVec___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _octra.IIVec___delitem__(self, *args)

    def __getitem__(self, *args):
        return _octra.IIVec___getitem__(self, *args)

    def __setitem__(self, *args):
        return _octra.IIVec___setitem__(self, *args)

    def pop(self):
        return _octra.IIVec_pop(self)

    def append(self, x):
        return _octra.IIVec_append(self, x)

    def empty(self):
        return _octra.IIVec_empty(self)

    def size(self):
        return _octra.IIVec_size(self)

    def swap(self, v):
        return _octra.IIVec_swap(self, v)

    def begin(self):
        return _octra.IIVec_begin(self)

    def end(self):
        return _octra.IIVec_end(self)

    def rbegin(self):
        return _octra.IIVec_rbegin(self)

    def rend(self):
        return _octra.IIVec_rend(self)

    def clear(self):
        return _octra.IIVec_clear(self)

    def get_allocator(self):
        return _octra.IIVec_get_allocator(self)

    def pop_back(self):
        return _octra.IIVec_pop_back(self)

    def erase(self, *args):
        return _octra.IIVec_erase(self, *args)

    def __init__(self, *args):
        _octra.IIVec_swiginit(self, _octra.new_IIVec(*args))

    def push_back(self, x):
        return _octra.IIVec_push_back(self, x)

    def front(self):
        return _octra.IIVec_front(self)

    def back(self):
        return _octra.IIVec_back(self)

    def assign(self, n, x):
        return _octra.IIVec_assign(self, n, x)

    def resize(self, *args):
        return _octra.IIVec_resize(self, *args)

    def insert(self, *args):
        return _octra.IIVec_insert(self, *args)

    def reserve(self, n):
        return _octra.IIVec_reserve(self, n)

    def capacity(self):
        return _octra.IIVec_capacity(self)
    __swig_destroy__ = _octra.delete_IIVec

# Register IIVec in _octra:
_octra.IIVec_swigregister(IIVec)
class SizeVec(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _octra.SizeVec_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _octra.SizeVec___nonzero__(self)

    def __bool__(self):
        return _octra.SizeVec___bool__(self)

    def __len__(self):
        return _octra.SizeVec___len__(self)

    def __getslice__(self, i, j):
        return _octra.SizeVec___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _octra.SizeVec___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _octra.SizeVec___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _octra.SizeVec___delitem__(self, *args)

    def __getitem__(self, *args):
        return _octra.SizeVec___getitem__(self, *args)

    def __setitem__(self, *args):
        return _octra.SizeVec___setitem__(self, *args)

    def pop(self):
        return _octra.SizeVec_pop(self)

    def append(self, x):
        return _octra.SizeVec_append(self, x)

    def empty(self):
        return _octra.SizeVec_empty(self)

    def size(self):
        return _octra.SizeVec_size(self)

    def swap(self, v):
        return _octra.SizeVec_swap(self, v)

    def begin(self):
        return _octra.SizeVec_begin(self)

    def end(self):
        return _octra.SizeVec_end(self)

    def rbegin(self):
        return _octra.SizeVec_rbegin(self)

    def rend(self):
        return _octra.SizeVec_rend(self)

    def clear(self):
        return _octra.SizeVec_clear(self)

    def get_allocator(self):
        return _octra.SizeVec_get_allocator(self)

    def pop_back(self):
        return _octra.SizeVec_pop_back(self)

    def erase(self, *args):
        return _octra.SizeVec_erase(self, *args)

    def __init__(self, *args):
        _octra.SizeVec_swiginit(self, _octra.new_SizeVec(*args))

    def push_back(self, x):
        return _octra.SizeVec_push_back(self, x)

    def front(self):
        return _octra.SizeVec_front(self)

    def back(self):
        return _octra.SizeVec_back(self)

    def assign(self, n, x):
        return _octra.SizeVec_assign(self, n, x)

    def resize(self, *args):
        return _octra.SizeVec_resize(self, *args)

    def insert(self, *args):
        return _octra.SizeVec_insert(self, *args)

    def reserve(self, n):
        return _octra.SizeVec_reserve(self, n)

    def capacity(self):
        return _octra.SizeVec_capacity(self)
    __swig_destroy__ = _octra.delete_SizeVec

# Register SizeVec in _octra:
_octra.SizeVec_swigregister(SizeVec)
class DVec(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _octra.DVec_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _octra.DVec___nonzero__(self)

    def __bool__(self):
        return _octra.DVec___bool__(self)

    def __len__(self):
        return _octra.DVec___len__(self)

    def __getslice__(self, i, j):
        return _octra.DVec___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _octra.DVec___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _octra.DVec___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _octra.DVec___delitem__(self, *args)

    def __getitem__(self, *args):
        return _octra.DVec___getitem__(self, *args)

    def __setitem__(self, *args):
        return _octra.DVec___setitem__(self, *args)

    def pop(self):
        return _octra.DVec_pop(self)

    def append(self, x):
        return _octra.DVec_append(self, x)

    def empty(self):
        return _octra.DVec_empty(self)

    def size(self):
        return _octra.DVec_size(self)

    def swap(self, v):
        return _octra.DVec_swap(self, v)

    def begin(self):
        return _octra.DVec_begin(self)

    def end(self):
        return _octra.DVec_end(self)

    def rbegin(self):
        return _octra.DVec_rbegin(self)

    def rend(self):
        return _octra.DVec_rend(self)

    def clear(self):
        return _octra.DVec_clear(self)

    def get_allocator(self):
        return _octra.DVec_get_allocator(self)

    def pop_back(self):
        return _octra.DVec_pop_back(self)

    def erase(self, *args):
        return _octra.DVec_erase(self, *args)

    def __init__(self, *args):
        _octra.DVec_swiginit(self, _octra.new_DVec(*args))

    def push_back(self, x):
        return _octra.DVec_push_back(self, x)

    def front(self):
        return _octra.DVec_front(self)

    def back(self):
        return _octra.DVec_back(self)

    def assign(self, n, x):
        return _octra.DVec_assign(self, n, x)

    def resize(self, *args):
        return _octra.DVec_resize(self, *args)

    def insert(self, *args):
        return _octra.DVec_insert(self, *args)

    def reserve(self, n):
        return _octra.DVec_reserve(self, n)

    def capacity(self):
        return _octra.DVec_capacity(self)
    __swig_destroy__ = _octra.delete_DVec

# Register DVec in _octra:
_octra.DVec_swigregister(DVec)
class DDVec(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _octra.DDVec_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _octra.DDVec___nonzero__(self)

    def __bool__(self):
        return _octra.DDVec___bool__(self)

    def __len__(self):
        return _octra.DDVec___len__(self)

    def __getslice__(self, i, j):
        return _octra.DDVec___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _octra.DDVec___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _octra.DDVec___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _octra.DDVec___delitem__(self, *args)

    def __getitem__(self, *args):
        return _octra.DDVec___getitem__(self, *args)

    def __setitem__(self, *args):
        return _octra.DDVec___setitem__(self, *args)

    def pop(self):
        return _octra.DDVec_pop(self)

    def append(self, x):
        return _octra.DDVec_append(self, x)

    def empty(self):
        return _octra.DDVec_empty(self)

    def size(self):
        return _octra.DDVec_size(self)

    def swap(self, v):
        return _octra.DDVec_swap(self, v)

    def begin(self):
        return _octra.DDVec_begin(self)

    def end(self):
        return _octra.DDVec_end(self)

    def rbegin(self):
        return _octra.DDVec_rbegin(self)

    def rend(self):
        return _octra.DDVec_rend(self)

    def clear(self):
        return _octra.DDVec_clear(self)

    def get_allocator(self):
        return _octra.DDVec_get_allocator(self)

    def pop_back(self):
        return _octra.DDVec_pop_back(self)

    def erase(self, *args):
        return _octra.DDVec_erase(self, *args)

    def __init__(self, *args):
        _octra.DDVec_swiginit(self, _octra.new_DDVec(*args))

    def push_back(self, x):
        return _octra.DDVec_push_back(self, x)

    def front(self):
        return _octra.DDVec_front(self)

    def back(self):
        return _octra.DDVec_back(self)

    def assign(self, n, x):
        return _octra.DDVec_assign(self, n, x)

    def resize(self, *args):
        return _octra.DDVec_resize(self, *args)

    def insert(self, *args):
        return _octra.DDVec_insert(self, *args)

    def reserve(self, n):
        return _octra.DDVec_reserve(self, n)

    def capacity(self):
        return _octra.DDVec_capacity(self)
    __swig_destroy__ = _octra.delete_DDVec

# Register DDVec in _octra:
_octra.DDVec_swigregister(DDVec)
class DynArrayInt(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args):
        _octra.DynArrayInt_swiginit(self, _octra.new_DynArrayInt(*args))
    __swig_destroy__ = _octra.delete_DynArrayInt

    def reserve(self, capacity):
        return _octra.DynArrayInt_reserve(self, capacity)

    def push_back(self, *args):
        return _octra.DynArrayInt_push_back(self, *args)

    def clear(self):
        return _octra.DynArrayInt_clear(self)

    def capacity(self):
        return _octra.DynArrayInt_capacity(self)

    def size(self):
        return _octra.DynArrayInt_size(self)

    def to_string(self):
        return _octra.DynArrayInt_to_string(self)

    def _print(self):
        return _octra.DynArrayInt__print(self)

    def to_vec(self):
        return _octra.DynArrayInt_to_vec(self)

    def __repr__(self):
        return _octra.DynArrayInt___repr__(self)

    def __str__(self):
        return _octra.DynArrayInt___str__(self)

    def __setitem__(self, index, value):
        return _octra.DynArrayInt___setitem__(self, index, value)

    def __getitem__(self, index):
        return _octra.DynArrayInt___getitem__(self, index)

# Register DynArrayInt in _octra:
_octra.DynArrayInt_swigregister(DynArrayInt)
class DynArrayDouble(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args):
        _octra.DynArrayDouble_swiginit(self, _octra.new_DynArrayDouble(*args))
    __swig_destroy__ = _octra.delete_DynArrayDouble

    def reserve(self, capacity):
        return _octra.DynArrayDouble_reserve(self, capacity)

    def push_back(self, *args):
        return _octra.DynArrayDouble_push_back(self, *args)

    def clear(self):
        return _octra.DynArrayDouble_clear(self)

    def capacity(self):
        return _octra.DynArrayDouble_capacity(self)

    def size(self):
        return _octra.DynArrayDouble_size(self)

    def to_string(self):
        return _octra.DynArrayDouble_to_string(self)

    def _print(self):
        return _octra.DynArrayDouble__print(self)

    def to_vec(self):
        return _octra.DynArrayDouble_to_vec(self)

    def __repr__(self):
        return _octra.DynArrayDouble___repr__(self)

    def __str__(self):
        return _octra.DynArrayDouble___str__(self)

    def __setitem__(self, index, value):
        return _octra.DynArrayDouble___setitem__(self, index, value)

    def __getitem__(self, index):
        return _octra.DynArrayDouble___getitem__(self, index)

# Register DynArrayDouble in _octra:
_octra.DynArrayDouble_swigregister(DynArrayDouble)

